name: Validate PR
on: pull_request

defaults:
  run:
    shell: bash
    working-directory: project

jobs:
  test:
    runs-on: ubuntu-latest
    # outputs:
    #   files: ${{ steps.changed.outputs.files }}
    steps:     
      # checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project
          fetch-depth: 0
      # checkout schema as xmllint can't https 
      # - name: Checkout schema repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: BetaMasaheft/Schema
      #     path: schema
      - name: Install Test Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      # Compare locally changed files to PR's base
      - name: dummy color output
        id: dummy
        run: echo "color=green" >> "$GITHUB_OUTPUT" 
      - name: Get color
        env:
          COLOR: ${{ steps.dummy.outputs.COLOR }}
        run: echo "The selected color is $COLOR"
      - name: Check for changed source files
        id: changed
        run: |
          echo "FILES=$(git diff --name-only --diff-filter=ACMRT \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.sha }} -- '*.xml')"  | xargs
            >> "$GITHUB_OUTPUT"
      # -- './**/*.xml,*/transkribus*.xml,*/facsimile*.xml' | xargs
      - name: Log Output
        env:
          FILES: ${{ steps.changed.outputs.FILES }}
        run: 
          | 
          echo ${{ steps.changed.outputs.FILES }}
          echo $FILES
          echo ${FILES}
          echo "modified: $FILES"
      # Validate changed files against latest schema
      # - name: Validate changed source files
      #   if: ${{ steps.changed.outputs.files != '' }}
      #   run: |
      #     xmllint \
      #       --noout --xinclude --nowarning \
      #       --relaxng ../schema/tei-betamesaheft.rng \
      #       ${{ steps.changed.outputs.files }} \
      #       2>&1 | \
      #       { grep -vE 'RNG|validates' || :; }
      # If no xml files were modified
      - name: No source files changed
        if: ${{ steps.changed.outputs.files == '' }}
        run: |
          echo "All good"
      # ensure branch conaints only well-formed xml files 
      - name: Ensure all XML files are well formed
        run: |
          xmllint --noout \
            $(find . -type f -name '*.xml') 
